PP-3782 [CP] Field 'Percent owned' displays as fractional number
plyo/plyo.tools pull request #22
Opened 2021-01-28 07:56 UTC by ZhuravlevaS

Link to JIRA issue: https://plyolabs.atlassian.net/browse/PP-3782

Link to demo:  no

### What was changed?

remove zeros after dot with toFixed()

### Any related PRs? no

### What components were affected?

CustomerUnits.js

### Link to updated documentation regarding this PR
no

### Notes for QA

2021-01-29 20:05 UTC, jifeon approved these changes

2021-01-29 20:09 UTC, jifeon requested changes

2021-01-29 20:09 UTC, jifeon commented on lib/formatNumber.js
> +          ? Number(number.toPrecision(15)).toString()
Please add comments for the function which make clear what are you doing here :)

2021-01-29 20:12 UTC, jifeon commented
Also I think that precision should be an argument of the function with default value

2021-02-02 18:18 UTC, frenzzy approved these changes

2021-02-02 18:21 UTC, jifeon approved these changes

2021-02-02 18:21 UTC, merged

2021-02-02 18:28 UTC, jifeon commented
Published as plyo-tools@4.2.0